name: sh2021-python
channels:
  - conda-forge
dependencies:
  - python=3.7.10
  - jupyterlab=3.0.16
  - pandas=1.3.0
  - openpyxl=3.0.9
  - matplotlib=3.4.2
  - scikit-learn=0.24.1
  - xlrd=2.0.1
  - openpyxl=3.0.9
  - streamlit=1.2.0
  - xgboost=1.3.3
  